-- ============================================================================
-- ElGuindy Glass Invoicing System - PostgreSQL Export Script
-- ============================================================================
--
-- This script exports all tables from the PostgreSQL database as JSONL files
-- (one JSON object per line) that can be consumed by a Node.js import script.
--
-- Directory structure:
--   scripts/
--     export-postgres.sql   <-- this file
--   data/                   <-- output directory (must exist before running)
--     customer.jsonl
--     glass_type.jsonl
--     users.jsonl
--     invoice.jsonl
--     invoice_line.jsonl
--     invoice_line_operation.jsonl
--     payments.jsonl
--     print_job.jsonl
--     cutting_rates.jsonl
--     shataf_rates.jsonl
--     operation_prices.jsonl
--     company_profile.jsonl
--     notifications.jsonl
--
-- How to run:
--   1. Make sure the data/ directory exists:
--        mkdir -p data
--   2. Run from the project root directory:
--        psql -d <your_database_name> -f scripts/export-postgres.sql
--      For example:
--        psql -d elguindy -f scripts/export-postgres.sql
--      Or with full connection details:
--        psql -h localhost -p 5432 -U postgres -d elguindy -f scripts/export-postgres.sql
--
-- Notes:
--   - This assumes the default PostgreSQL table names generated by Spring Data JPA.
--   - The "Users" table is quoted because JPA maps it with an uppercase U.
--   - The data/ directory MUST exist before running this script, otherwise
--     the \copy commands will fail.
--   - Each output file is in JSONL format (one JSON object per line), which is
--     easy to parse line-by-line in Node.js using readline or split('\n').
--   - Tables are exported in dependency order so that foreign key references
--     can be resolved during import.
-- ============================================================================

-- 1. customer (no foreign keys - base table)
\copy (SELECT row_to_json(t) FROM (SELECT id, name, phone, address, customer_type, balance, created_at, updated_at FROM customer ORDER BY id) t) TO 'data/customer.jsonl'

-- 2. glass_type (no foreign keys - base table)
\copy (SELECT row_to_json(t) FROM (SELECT id, name, thickness, color, price_per_meter, calculation_method, active FROM glass_type ORDER BY id) t) TO 'data/glass_type.jsonl'

-- 3. "Users" (quoted, uppercase U - JPA default mapping)
\copy (SELECT row_to_json(t) FROM (SELECT id, username, password, first_name, last_name, role, is_active FROM "Users" ORDER BY id) t) TO 'data/users.jsonl'

-- 4. invoice (depends on: customer)
--    id is the readable string ID (e.g. "INV-2026-001"), customer_id is a Long FK to customer.id
\copy (SELECT row_to_json(t) FROM (SELECT id, customer_id, issue_date, payment_date, total_price, amount_paid_now, remaining_balance, status, work_status, notes, pdf_url, created_at, updated_at FROM invoice ORDER BY created_at) t) TO 'data/invoice.jsonl'

-- 5. invoice_line (depends on: invoice, glass_type)
--    invoice_id is a String FK matching invoice.id, glass_type_id is a Long FK
\copy (SELECT row_to_json(t) FROM (SELECT id, invoice_id, glass_type_id, width, height, dimension_unit, diameter, area_m2, length_m, quantity, shataf_meters, cutting_type, shataf_type, farma_type, manual_cutting_price, cutting_price, cutting_rate, glass_price, line_total, notes, status FROM invoice_line ORDER BY id) t) TO 'data/invoice_line.jsonl'

-- 6. invoice_line_operation (depends on: invoice_line)
--    invoice_line_id is a Long FK to invoice_line.id
\copy (SELECT row_to_json(t) FROM (SELECT id, invoice_line_id, operation_type, shataf_type, farma_type, diameter, manual_cutting_price, laser_type, manual_price, notes, shataf_meters, rate_per_meter, operation_price FROM invoice_line_operation ORDER BY id) t) TO 'data/invoice_line_operation.jsonl'

-- 7. payments (depends on: customer, invoice)
--    customer_id is a Long FK, invoice_id is a String FK (nullable)
\copy (SELECT row_to_json(t) FROM (SELECT id, customer_id, invoice_id, amount, payment_method, payment_date, reference_number, notes, created_at, created_by FROM payments ORDER BY id) t) TO 'data/payments.jsonl'

-- 8. print_job (depends on: invoice, invoice_line)
--    invoice_id is a String FK, invoice_line_id is a Long FK (nullable)
\copy (SELECT row_to_json(t) FROM (SELECT id, invoice_id, invoice_line_id, type, status, pdf_path, error_message, created_at, printed_at FROM print_job ORDER BY id) t) TO 'data/print_job.jsonl'

-- 9. cutting_rates (no foreign keys - configuration table)
\copy (SELECT row_to_json(t) FROM (SELECT id, cutting_type, min_thickness, max_thickness, rate_per_meter, active FROM cutting_rates ORDER BY id) t) TO 'data/cutting_rates.jsonl'

-- 10. shataf_rates (no foreign keys - configuration table)
\copy (SELECT row_to_json(t) FROM (SELECT id, shataf_type, min_thickness, max_thickness, rate_per_meter, active, created_at, updated_at FROM shataf_rates ORDER BY id) t) TO 'data/shataf_rates.jsonl'

-- 11. operation_prices (no foreign keys - configuration table)
\copy (SELECT row_to_json(t) FROM (SELECT id, operation_type, subtype, arabic_name, english_name, base_price, unit, description, active, display_order FROM operation_prices ORDER BY id) t) TO 'data/operation_prices.jsonl'

-- 12. company_profile (no foreign keys - singleton configuration)
\copy (SELECT row_to_json(t) FROM (SELECT id, company_name, company_name_arabic, address, phone, email, tax_id, commercial_register, logo_url, logo_base64, logo_content_type, footer_text FROM company_profile ORDER BY id) t) TO 'data/company_profile.jsonl'

-- 13. notifications (depends on: "Users" via user_id UUID FK, nullable)
\copy (SELECT row_to_json(t) FROM (SELECT id, user_id, title, message, type, action_url, created_at, is_read, related_entity, read_by_users, hidden_by_users FROM notifications ORDER BY id) t) TO 'data/notifications.jsonl'

-- ============================================================================
-- Export complete. Check the data/ directory for output files.
-- ============================================================================
